# Generated by Django 4.0.6 on 2022-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pixelplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('paragrafo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='servicos2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('paragrafo', models.TextField()),
            ],
        ),
    ]
