# Generated by Django 4.0.6 on 2022-07-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pixelplus', '0002_servicos1_servicos2'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientes', models.CharField(max_length=4)),
                ('projetos', models.CharField(max_length=4)),
                ('premios', models.CharField(max_length=4)),
            ],
        ),
    ]
