# Generated by Django 4.0.6 on 2022-07-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pixelplus', '0003_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='trabalhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotos')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
    ]
