# Generated by Django 4.0.6 on 2022-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pixelplus', '0005_rename_titulo_trabalhos_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotos')),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('depoimento', models.TextField()),
            ],
        ),
    ]
