# Generated by Django 4.0.6 on 2022-07-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pixelplus', '0007_formcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('twitter', models.CharField(max_length=150)),
            ],
        ),
    ]
